// <auto-generated />
using System;
using GardenService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenService.Migrations
{
    [DbContext(typeof(GardenServicesDbContext))]
    [Migration("20211127215246_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("GardenService.Models.Moisture", b =>
                {
                    b.Property<int>("IX_Moisture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EnteredDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("IX_Moisture");

                    b.ToTable("Moistures");

                    b.HasData(
                        new
                        {
                            IX_Moisture = 1,
                            EnteredDate = new DateTime(2021, 11, 27, 15, 52, 46, 424, DateTimeKind.Local).AddTicks(7247),
                            Value = 1.4f
                        },
                        new
                        {
                            IX_Moisture = 2,
                            EnteredDate = new DateTime(2021, 11, 27, 15, 52, 46, 424, DateTimeKind.Local).AddTicks(7288),
                            Value = 1.5f
                        },
                        new
                        {
                            IX_Moisture = 3,
                            EnteredDate = new DateTime(2021, 11, 27, 15, 52, 46, 424, DateTimeKind.Local).AddTicks(7292),
                            Value = 1.6f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
